{
  "openapi": "3.0.0",
  "info": {
    "title": "RentX Documentation",
    "description": "This is an API Rent",
    "version": "1.0.1",
    "contact": {
      "email": "oi@marcon.run"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3000",
      "description": "Local Server"
    }
  ],
  "paths": {
    "/client": {
      "post": {
        "tags": [
          "Client"
        ],
        "summary": "Create a client",
        "description": "Create a new client",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "username": "themark",
                  "password": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Client already exist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Client already exist"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/client/authenticate": {
      "post": {
        "tags": [
          "Client",
          "Authentication"
        ],
        "summary": "Create a session to client",
        "description": "Create a session to client",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "username": "themark",
                  "password": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Username or password invalid",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Username or password invalid"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/deliveryman": {
      "post": {
        "tags": [
          "Deliveryman"
        ],
        "summary": "Create a deliveryman",
        "description": "Create a new deliveryman",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "username": "themark",
                  "password": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created"
          },
          "400": {
            "description": "Deliveryman already exist",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Deliveryman already exist"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/deliveryman/authenticate": {
      "post": {
        "tags": [
          "Deliveryman",
          "Authentication"
        ],
        "summary": "Create a session to deliveryman",
        "description": "Create a session to deliveryman",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                },
                "example": {
                  "username": "themark",
                  "password": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Username or password invalid",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "message": "Username or password invalid"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/delivery": {
      "post": {
        "tags": [
          "Delivery"
        ],
        "summary": "Create a delivery",
        "description": "Create a delivery",
        "security": [
          {
            "BearerClientToken": []
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "item_name": {
                    "type": "string"
                  }
                },
                "example": {
                  "item_name": "Coca Cola"
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "id_client": {
                      "type": "string"
                    },
                    "id_deliveryman": {
                      "type": "string"
                    },
                    "item_name": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "end_at": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "1d3f6d69-5a40-4080-a037-5cc696972524",
                    "id_client": "4e8bd6c4-6e7c-4ceb-9428-90fd1e4ecab3",
                    "id_deliveryman": null,
                    "item_name": "Coca Cola",
                    "created_at": "2022-04-10T02:29:52.140Z",
                    "end_at": null
                  }
                }
              }
            }
          }
        }
      }
    },
    "/delivery/available": {
      "get": {
        "tags": [
          "Delivery"
        ],
        "summary": "Get all deliveries available",
        "description": "Get all deliveries available",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "example": [{
                    "id": "1d3f6d69-5a40-4080-a037-5cc696972524",
                    "id_client": "4e8bd6c4-6e7c-4ceb-9428-90fd1e4ecab3",
                    "id_deliveryman": null,
                    "item_name": "Coca Cola",
                    "created_at": "2022-04-10T02:29:52.140Z",
                    "end_at": null
                  }],
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": {
                        "type": "string"
                      },
                      "id_client": {
                        "type": "string"
                      },
                      "id_deliveryman": {
                        "type": "string"
                      },
                      "item_name": {
                        "type": "string"
                      },
                      "created_at": {
                        "type": "string"
                      },
                      "end_at": {
                        "type": "string"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/delivery/{ idDelivery }/updateDeliveryman": {
      "put": {
        "tags": [
          "Delivery"
        ],
        "summary": "Update deliveryman from delivery",
        "description": "Update deliveryman from delivery",
        "parameters": [{
          "name": "idDelivery",
          "in": "path",
          "description": "Delivery ID",
          "required": true,
          "schema": {
            "type": "string"
          }
        }],
        "security": [
          {
            "BearerTokenDeliveryman": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string"
                    },
                    "id_client": {
                      "type": "string"
                    },
                    "id_deliveryman": {
                      "type": "string"
                    },
                    "item_name": {
                      "type": "string"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "end_at": {
                      "type": "string"
                    }
                  },
                  "example": {
                    "id": "1d3f6d69-5a40-4080-a037-5cc696972524",
                    "id_client": "4e8bd6c4-6e7c-4ceb-9428-90fd1e4ecab3",
                    "id_deliveryman": null,
                    "item_name": "Coca Cola",
                    "created_at": "2022-04-10T02:29:52.140Z",
                    "end_at": null
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "BearerClientToken": {
        "description": "Client JTW Bearer Token",
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      },
      "BearerTokenDeliveryman": {
        "description": "Deliveryman JTW Bearer Token",
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "ok": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        }
      }
    }
  },
  "tags": [
    {
      "name": "Authentication"
    },
    {
      "name": "Client"
    },
    {
      "name": "Deliveryman"
    }
  ]
}